language: java
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm prune
script:
- npm run build
- npm test
- mvn clean javadoc:javadoc
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: sqlparser
  - GH_REPO: autoJavaDoc
  - secure: KazjYJTgyk75RUKMNuBvpK/RvoRWxS5JBTpEdaE3gwKXYcDkfcaM6DpCRl78D5X0Wv5NfaL22UScK3hHQtCIDKYCTWmY2FSZxwFRnCAZaZyUdOQQjIt9kJ+dm3mtTzb8DkNNpl9QCXQmNt1evVCGT5M2ENX6HKwASOAHmEr2Feubb0uE8yDCzEODL7zK04tvR4e6S4bo8IRcquSVhbnh9J4rCQlWBhoZ4QXo3jJdcr7h7hHuYYblv2C9GjmPLd8mH3V+vvM9wXHDYIh5+GuCSit4YGFz3BjN9qksgdyhI3HwK8ZT01UpVNe/ma46TSyXjYMDEC/hDvYC9fTElszR8vup3GyEG8CHiCLJ8sgqXA9zA/Tvnm1GraOE0x85+OslxdU62LmfNBVeljNjonmbSxfKOMlXmCsF54J4MXtj2N8mrVEY2N+P3VItpJfDrR8cmmGUcj85yxcXXc0GelSz1AnKjWlqg58f8HZgk4A7K+82oTRArR7WnNLZB03/XpfkD7xloHxwLEyNE8yu8wBEjKYJ+UzV4LWbBzJw5j940lqEjOWZ4joeDKpP6rI4BSvtNlS5+Arbc3UMV8ucM0Y2vAw84bgfR/FdzkXa6BKgZSNGV12UfRIrP6xkjWQjACfkA+N/lsCjJ/kUaaC9mth3+igi1YWrbXDZojaTUc9YSTo=
